/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Design;

import java.awt.Color;
import Database.*;
import Model.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Big Nigga Dude
 */
public class CatalogFrame extends javax.swing.JFrame {

    DAO myDao = new DAO();
    Model myMod;
    String category = "Semua Kategori", order = "ASC";
    int index = 0, total = 0;
    Image img = null;
    ImageIcon imgIcn = null;
    int indexKeranjang = 0;

    public CatalogFrame(Model mod) {
        initComponents();
        myMod = mod;
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                int res = JOptionPane.showConfirmDialog(null, "Ingin Keluar", "Mutia Vapestore : Login", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (res == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            }
        });
        run();
        setCB();
        setProductDetail();
        setLogo();
        setTroliTbl();
    }

    //====== METHODE ======
    public void setLogo() {
        try {
            img = Toolkit.getDefaultToolkit().createImage(myDao.frameLogo(1));
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        imgIcn = new ImageIcon(img.getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        logoContainer.setIcon(imgIcn);
        logoContainer.setText("");
    }

    public void setCB() {
        kategoriCB.removeAllItems();
        kategoriCB.addItem("Semua Kategori");
        for (String x : myDao.categoryList()) {
            kategoriCB.addItem(x);
        }
        produkCB.removeAllItems();
        for (String x : myDao.productList(category, order)) {
            produkCB.addItem(x);
        }

    }

    public void setFullSizeImg(byte[] path) {
        img = Toolkit.getDefaultToolkit().createImage(path);
        imgIcn = new ImageIcon(img.getScaledInstance(500, 500, Image.SCALE_DEFAULT));
        imageCont.setIcon(imgIcn);
        imageCont.setText("");
    }

    public void setProductDetail() {
        myMod.produk.setNamaProduk(produkCB.getItemAt(index));
        namaTF.setText((String) myDao.showProduk(myMod).get(0));
        kategoriTF.setText((String) myDao.showProduk(myMod).get(1));
        byte[] path = (byte[]) myDao.showProduk(myMod).get(2);
        img = Toolkit.getDefaultToolkit().createImage(path);
        imgIcn = new ImageIcon(img.getScaledInstance(180, 180, Image.SCALE_DEFAULT));
        gambarCont.setIcon(imgIcn);
        gambarCont.setText("");
        stokTF.setText(String.valueOf(myDao.showProduk(myMod).get(3)));
        hargaTF.setText(String.valueOf(myDao.showProduk(myMod).get(4)));
        setFullSizeImg(path);
    }

    public void setStokList() {
        for (int x = 1; x <= myDao.stokProduk(myMod, "id"); x++) {
            penjualanJumlahCB.addItem(String.valueOf(x));
        }
    }

    public void setTroliTbl() {
       troliTbl.setModel(myDao.showKeranjangJual());
       totalTransaksiLbl.setText(String.valueOf(myDao.totalKeranjangJual()));
    }

    public boolean checkAngka(String str) {
        boolean cek = true;
        if (str.length() > 0) {
            for (int x = 0; x < str.length(); x++) {
                if (!(str.charAt(x) >= '0' && str.charAt(x) <= '9') || str.charAt(0) == '0') {
                    cek = false;
                }
            }
        }
        return cek;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FullSizeImage = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        imageCont = new javax.swing.JLabel();
        PenjualanDialog = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        penjualanJumlahCB = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        penjualanNamaProdukLbl = new javax.swing.JLabel();
        penjualanTotalLbl = new javax.swing.JLabel();
        penjualanSubHargaLbl = new javax.swing.JLabel();
        jumlahOkBtn = new javax.swing.JButton();
        tambahkanBtn = new javax.swing.JButton();
        TroliDialog = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        troliTbl = new javax.swing.JTable();
        checkOutBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        totalTransaksiLbl = new javax.swing.JLabel();
        hapusProdukBtn = new javax.swing.JButton();
        editJumlahBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        gambarCont = new javax.swing.JLabel();
        namaTF = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stokTF = new javax.swing.JLabel();
        kategoriTF = new javax.swing.JLabel();
        hargaTF = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lihatGambarPenuhBtn = new javax.swing.JButton();
        beliSekarangBtn = new javax.swing.JButton();
        troliBtrn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        produkCB = new javax.swing.JComboBox<>();
        hargaCB = new javax.swing.JComboBox<>();
        kategoriCB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        setFilterBtn = new javax.swing.JButton();
        showDataProdukBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        logoContainer = new javax.swing.JLabel();
        katalogBtn = new javax.swing.JButton();
        pembelianBtn = new javax.swing.JButton();
        serviceBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();

        jPanel6.setBackground(new java.awt.Color(153, 0, 51));

        imageCont.setText("jLabel2");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(imageCont)
                .addContainerGap(506, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(imageCont)
                .addContainerGap(542, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FullSizeImageLayout = new javax.swing.GroupLayout(FullSizeImage.getContentPane());
        FullSizeImage.getContentPane().setLayout(FullSizeImageLayout);
        FullSizeImageLayout.setHorizontalGroup(
            FullSizeImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FullSizeImageLayout.setVerticalGroup(
            FullSizeImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(153, 0, 51));

        jLabel2.setFont(new java.awt.Font("Electroharmonix", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("~ tambah ke troli ~");

        penjualanJumlahCB.setBackground(new java.awt.Color(255, 255, 255));
        penjualanJumlahCB.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nama Produk ");

        jLabel13.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Sub Harga");

        jLabel14.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Jumlah ");

        jLabel16.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(":");

        jLabel17.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Total");

        jLabel18.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(":");

        jLabel19.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(":");

        jLabel20.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(":");

        penjualanNamaProdukLbl.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        penjualanNamaProdukLbl.setForeground(new java.awt.Color(255, 255, 255));
        penjualanNamaProdukLbl.setText("Nama Produk ");

        penjualanTotalLbl.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        penjualanTotalLbl.setForeground(new java.awt.Color(255, 255, 255));
        penjualanTotalLbl.setText("Total");

        penjualanSubHargaLbl.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        penjualanSubHargaLbl.setForeground(new java.awt.Color(255, 255, 255));
        penjualanSubHargaLbl.setText("Sub Harga");

        jumlahOkBtn.setBackground(new java.awt.Color(0, 0, 0));
        jumlahOkBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jumlahOkBtn.setForeground(new java.awt.Color(255, 255, 255));
        jumlahOkBtn.setText("OK");
        jumlahOkBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jumlahOkBtnMouseClicked(evt);
            }
        });

        tambahkanBtn.setBackground(new java.awt.Color(0, 0, 0));
        tambahkanBtn.setFont(new java.awt.Font("Electroharmonix", 1, 24)); // NOI18N
        tambahkanBtn.setForeground(new java.awt.Color(255, 255, 255));
        tambahkanBtn.setText("tambahkan");
        tambahkanBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahkanBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(penjualanTotalLbl))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(penjualanJumlahCB, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jumlahOkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(penjualanNamaProdukLbl))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(penjualanSubHargaLbl))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(tambahkanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(82, 82, 82))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(penjualanNamaProdukLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel18)
                    .addComponent(penjualanSubHargaLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(penjualanJumlahCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jumlahOkBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(penjualanTotalLbl))
                .addGap(27, 27, 27)
                .addComponent(tambahkanBtn)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PenjualanDialogLayout = new javax.swing.GroupLayout(PenjualanDialog.getContentPane());
        PenjualanDialog.getContentPane().setLayout(PenjualanDialogLayout);
        PenjualanDialogLayout.setHorizontalGroup(
            PenjualanDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PenjualanDialogLayout.setVerticalGroup(
            PenjualanDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(153, 0, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        troliTbl.setBackground(new java.awt.Color(153, 0, 51));
        troliTbl.setFont(new java.awt.Font("Swis721 BT", 1, 12)); // NOI18N
        troliTbl.setForeground(new java.awt.Color(255, 255, 255));
        troliTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        troliTbl.setFocusCycleRoot(true);
        troliTbl.setGridColor(new java.awt.Color(153, 0, 51));
        troliTbl.setSelectionBackground(new java.awt.Color(0, 0, 0));
        troliTbl.setShowGrid(true);
        troliTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                troliTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(troliTbl);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 175, -1, 85));

        checkOutBtn.setBackground(new java.awt.Color(0, 0, 0));
        checkOutBtn.setFont(new java.awt.Font("Electroharmonix", 1, 36)); // NOI18N
        checkOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkOutBtn.setText("CHECK OUT");
        checkOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkOutBtnMouseClicked(evt);
            }
        });
        jPanel8.add(checkOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 387, -1, -1));

        jLabel15.setFont(new java.awt.Font("Electroharmonix", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("TOTAL TRANSAKSI :");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 320, -1, -1));

        jLabel22.setFont(new java.awt.Font("Electroharmonix", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("~ TROLI ~");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 55, -1, -1));

        totalTransaksiLbl.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        totalTransaksiLbl.setForeground(new java.awt.Color(255, 255, 255));
        totalTransaksiLbl.setText("TOTAL TRANSAKSI :");
        jPanel8.add(totalTransaksiLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 320, -1, -1));

        hapusProdukBtn.setText("hapus");
        hapusProdukBtn.setEnabled(false);
        hapusProdukBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusProdukBtnMouseClicked(evt);
            }
        });
        jPanel8.add(hapusProdukBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 278, 76, -1));

        editJumlahBtn.setText("edit Jumlah");
        editJumlahBtn.setEnabled(false);
        editJumlahBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editJumlahBtnMouseClicked(evt);
            }
        });
        jPanel8.add(editJumlahBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 278, -1, -1));

        javax.swing.GroupLayout TroliDialogLayout = new javax.swing.GroupLayout(TroliDialog.getContentPane());
        TroliDialog.getContentPane().setLayout(TroliDialogLayout);
        TroliDialogLayout.setHorizontalGroup(
            TroliDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TroliDialogLayout.setVerticalGroup(
            TroliDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 691, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gambarCont.setText("GAMBAR");
        jPanel2.add(gambarCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        namaTF.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        namaTF.setForeground(new java.awt.Color(255, 255, 255));
        namaTF.setText("Nama");
        jPanel2.add(namaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kategori");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Stok");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Harga");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nama");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        stokTF.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        stokTF.setForeground(new java.awt.Color(255, 255, 255));
        stokTF.setText("Stok");
        jPanel2.add(stokTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        kategoriTF.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        kategoriTF.setForeground(new java.awt.Color(255, 255, 255));
        kategoriTF.setText("Kategori");
        jPanel2.add(kategoriTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        hargaTF.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        hargaTF.setForeground(new java.awt.Color(255, 255, 255));
        hargaTF.setText("Harga");
        jPanel2.add(hargaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Electroharmonix", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("~ data produk ~");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 6, -1, -1));

        lihatGambarPenuhBtn.setBackground(new java.awt.Color(0, 0, 0));
        lihatGambarPenuhBtn.setFont(new java.awt.Font("Electroharmonix", 1, 14)); // NOI18N
        lihatGambarPenuhBtn.setForeground(new java.awt.Color(255, 255, 255));
        lihatGambarPenuhBtn.setText("LIHAT GAMBAR PENUH");
        lihatGambarPenuhBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lihatGambarPenuhBtnMouseClicked(evt);
            }
        });
        jPanel2.add(lihatGambarPenuhBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 200, -1));

        beliSekarangBtn.setBackground(new java.awt.Color(0, 0, 0));
        beliSekarangBtn.setFont(new java.awt.Font("Electroharmonix", 1, 15)); // NOI18N
        beliSekarangBtn.setForeground(new java.awt.Color(255, 255, 255));
        beliSekarangBtn.setText("tambah ke troli");
        beliSekarangBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beliSekarangBtnMouseClicked(evt);
            }
        });
        beliSekarangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliSekarangBtnActionPerformed(evt);
            }
        });
        jPanel2.add(beliSekarangBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 200, 50));

        troliBtrn.setBackground(new java.awt.Color(0, 0, 0));
        troliBtrn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/Shopping-Cart-01-52.png"))); // NOI18N
        troliBtrn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                troliBtrnMouseClicked(evt);
            }
        });
        jPanel2.add(troliBtrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 570, 310));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 590, 30));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 660, 590, 30));

        produkCB.setBackground(new java.awt.Color(255, 255, 255));
        produkCB.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 14)); // NOI18N
        produkCB.setForeground(new java.awt.Color(255, 255, 255));
        produkCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Termurah", "Termahal", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", " ", "w", "w", "w", "w", " " }));
        jPanel1.add(produkCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 430, -1));

        hargaCB.setBackground(new java.awt.Color(255, 255, 255));
        hargaCB.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 14)); // NOI18N
        hargaCB.setForeground(new java.awt.Color(255, 255, 255));
        hargaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Termurah", "Termahal" }));
        jPanel1.add(hargaCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 130, -1));

        kategoriCB.setBackground(new java.awt.Color(255, 255, 255));
        kategoriCB.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 14)); // NOI18N
        kategoriCB.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(kategoriCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 130, -1));

        jLabel4.setFont(new java.awt.Font("Electroharmonix", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("produk list");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Electroharmonix", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 51));
        jLabel9.setText("Harga");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Electroharmonix", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 51));
        jLabel10.setText("~ KATALOG ~");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        setFilterBtn.setBackground(new java.awt.Color(0, 0, 0));
        setFilterBtn.setFont(new java.awt.Font("Electroharmonix", 1, 14)); // NOI18N
        setFilterBtn.setForeground(new java.awt.Color(255, 255, 255));
        setFilterBtn.setText("TERAPKAN FILTER");
        setFilterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setFilterBtnMouseClicked(evt);
            }
        });
        jPanel1.add(setFilterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        showDataProdukBtn.setBackground(new java.awt.Color(0, 0, 0));
        showDataProdukBtn.setFont(new java.awt.Font("Electroharmonix", 1, 14)); // NOI18N
        showDataProdukBtn.setForeground(new java.awt.Color(255, 255, 255));
        showDataProdukBtn.setText("TAMPILKAN DATA PRODUK");
        showDataProdukBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showDataProdukBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showDataProdukBtnMouseEntered(evt);
            }
        });
        showDataProdukBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDataProdukBtnActionPerformed(evt);
            }
        });
        jPanel1.add(showDataProdukBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Electroharmonix", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 51));
        jLabel11.setText("kategori");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jPanel3.setBackground(new java.awt.Color(153, 0, 51));

        logoContainer.setText("jLabel3");

        katalogBtn.setBackground(new java.awt.Color(0, 0, 0));
        katalogBtn.setFont(new java.awt.Font("Electroharmonix", 1, 24)); // NOI18N
        katalogBtn.setForeground(new java.awt.Color(255, 255, 255));
        katalogBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/E-Service-WF-52.png"))); // NOI18N
        katalogBtn.setText(" KATALOG    ");
        katalogBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        katalogBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                katalogBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                katalogBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                katalogBtnMouseExited(evt);
            }
        });

        pembelianBtn.setBackground(new java.awt.Color(153, 0, 51));
        pembelianBtn.setFont(new java.awt.Font("Electroharmonix", 1, 24)); // NOI18N
        pembelianBtn.setForeground(new java.awt.Color(255, 255, 255));
        pembelianBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/Shopping-Cart-01-52.png"))); // NOI18N
        pembelianBtn.setText(" Pembelian");
        pembelianBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pembelianBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pembelianBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pembelianBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pembelianBtnMouseExited(evt);
            }
        });

        serviceBtn.setBackground(new java.awt.Color(153, 0, 51));
        serviceBtn.setFont(new java.awt.Font("Electroharmonix", 1, 24)); // NOI18N
        serviceBtn.setForeground(new java.awt.Color(255, 255, 255));
        serviceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/Tools-02-52.png"))); // NOI18N
        serviceBtn.setText(" SErvice    ");
        serviceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serviceBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                serviceBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                serviceBtnMouseExited(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(153, 0, 51));
        exitBtn.setFont(new java.awt.Font("Electroharmonix", 1, 24)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/Exit-03-48.png"))); // NOI18N
        exitBtn.setText(" EXIT          ");
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.setPreferredSize(new java.awt.Dimension(135, 60));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
        });
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        homeBtn.setBackground(new java.awt.Color(153, 0, 51));
        homeBtn.setFont(new java.awt.Font("Electroharmonix", 1, 24)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/Home-52.png"))); // NOI18N
        homeBtn.setText(" HOME            ");
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(katalogBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(logoContainer))
                        .addComponent(pembelianBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(serviceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(logoContainer)
                .addGap(44, 44, 44)
                .addComponent(homeBtn)
                .addGap(18, 18, 18)
                .addComponent(katalogBtn)
                .addGap(18, 18, 18)
                .addComponent(pembelianBtn)
                .addGap(18, 18, 18)
                .addComponent(serviceBtn)
                .addGap(98, 98, 98)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 691));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setFilterBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setFilterBtnMouseClicked
        if (hargaCB.getSelectedIndex() == 0) {
            order = "asc";
        } else {
            order = "desc";
        }
        category = kategoriCB.getSelectedItem().toString();
        index = 0;
        setCB();
        kategoriCB.setSelectedItem(category);
        setProductDetail();

    }//GEN-LAST:event_setFilterBtnMouseClicked

    private void showDataProdukBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showDataProdukBtnMouseClicked
        produkCB.setSelectedItem(produkCB.getSelectedItem());
        myDao.showProduk(myMod);
        index = produkCB.getSelectedIndex();
        setProductDetail();
    }//GEN-LAST:event_showDataProdukBtnMouseClicked

    private void lihatGambarPenuhBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihatGambarPenuhBtnMouseClicked
        FullSizeImage.setSize(600, 600);
        FullSizeImage.setResizable(false);
        FullSizeImage.setLocationRelativeTo(null);
        FullSizeImage.setVisible(true);

    }//GEN-LAST:event_lihatGambarPenuhBtnMouseClicked

    private void beliSekarangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliSekarangBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beliSekarangBtnActionPerformed

    private void beliSekarangBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beliSekarangBtnMouseClicked
        penjualanJumlahCB.removeAllItems();
        setStokList();
        penjualanNamaProdukLbl.setText(namaTF.getText());
        penjualanSubHargaLbl.setText(hargaTF.getText());
        total = Integer.parseInt(penjualanJumlahCB.getItemAt(0)) * Integer.parseInt(hargaTF.getText());
        penjualanTotalLbl.setText(String.valueOf(total));
        PenjualanDialog.setVisible(true);
    }//GEN-LAST:event_beliSekarangBtnMouseClicked

    private void jumlahOkBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jumlahOkBtnMouseClicked
        total = Integer.parseInt(penjualanJumlahCB.getItemAt(penjualanJumlahCB.getSelectedIndex())) * Integer.parseInt(hargaTF.getText());
        penjualanTotalLbl.setText(String.valueOf(total));
    }//GEN-LAST:event_jumlahOkBtnMouseClicked

    private void tambahkanBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahkanBtnMouseClicked
        int total = Integer.parseInt(penjualanJumlahCB.getItemAt(penjualanJumlahCB.getSelectedIndex())) * Integer.parseInt(hargaTF.getText());
        int res = JOptionPane.showConfirmDialog(null, "Apa Pesanan Anda Sudah Benar ?\nNama Produk : " + myMod.produk.getNamaProduk() + "\n"
                + "Sub Harga       : " + Integer.parseInt(hargaTF.getText()) + "\n"
                + "Jumlah             : " + penjualanJumlahCB.getItemAt(penjualanJumlahCB.getSelectedIndex()) + "\n"
                + "Total                  : " + total, "Mutia Vapestore : Penjualan", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        myMod.produk.setHarga(Integer.parseInt(hargaTF.getText()));
        myMod.penjualan.setJumlah(Integer.parseInt(penjualanJumlahCB.getItemAt(penjualanJumlahCB.getSelectedIndex())));
        if (res == JOptionPane.YES_OPTION) {
            if (myMod.penjualan.getKeranjang(myMod.penjualan).size() == 0) {
                System.out.println("Index kosong");
                myDao.insertKeranjangJual(myMod.produk.getNamaProduk() ,Integer.parseInt(hargaTF.getText()) , Integer.parseInt(penjualanJumlahCB.getItemAt(penjualanJumlahCB.getSelectedIndex())),Integer.parseInt(hargaTF.getText())*Integer.parseInt(penjualanJumlahCB.getItemAt(penjualanJumlahCB.getSelectedIndex())));
            }
            
            PenjualanDialog.dispose();
            setProductDetail();
        }


    }//GEN-LAST:event_tambahkanBtnMouseClicked

    private void katalogBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_katalogBtnMouseClicked
        JOptionPane.showMessageDialog(null, "Anda Sedang Di Menu Katalog", "Mutia Vapestore : Katalog", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_katalogBtnMouseClicked

    private void katalogBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_katalogBtnMouseEntered
        katalogBtn.setBackground(new Color(153, 0, 51));
    }//GEN-LAST:event_katalogBtnMouseEntered

    private void katalogBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_katalogBtnMouseExited
        katalogBtn.setBackground(Color.black);
    }//GEN-LAST:event_katalogBtnMouseExited

    private void pembelianBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembelianBtnMouseEntered
        pembelianBtn.setBackground(Color.black);
    }//GEN-LAST:event_pembelianBtnMouseEntered

    private void pembelianBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembelianBtnMouseExited
        pembelianBtn.setBackground(new Color(153, 0, 51));
    }//GEN-LAST:event_pembelianBtnMouseExited

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        MainFrame mf = new MainFrame(myMod);
        this.dispose();
    }//GEN-LAST:event_homeBtnMouseClicked

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        homeBtn.setBackground(Color.black);
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        homeBtn.setBackground(new Color(153, 0, 51));
    }//GEN-LAST:event_homeBtnMouseExited

    private void troliBtrnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_troliBtrnMouseClicked

        TroliDialog.setVisible(true);
        setTroliTbl();
    }//GEN-LAST:event_troliBtrnMouseClicked

    private void checkOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkOutBtnMouseClicked
        boolean canBuy = true;
        ArrayList<String> buffer = new ArrayList<>();
        StringBuffer sb = new StringBuffer();
     
        if (totalTransaksiLbl.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Anda Belum Memesan Apapun", "Mutia Vapestore : Troli", JOptionPane.INFORMATION_MESSAGE);
        } else {
                    
               for(int x=0;x<troliTbl.getRowCount();x++){
                   myMod.produk.setNamaProduk((String) troliTbl.getValueAt(x,0));
                   if (Integer.parseInt((String) troliTbl.getValueAt(x, 2).toString()) > myDao.stokProduk(myMod, "nama")) {
                        canBuy=false;
                }
               }
               
        
            if (canBuy) {
                myMod.penjualan.setTotalTransaksi(Integer.parseInt(totalTransaksiLbl.getText().toString()));
                myDao.insertPenjualan(myMod);
                setTroliTbl();
            } else {
                
                JOptionPane.showMessageDialog(null, "Tidak Bisa CheckOut :Karena Ada Barang yang akan dibeli melebihi stok \nSilahkan edit jumlah nya atau hapus", "Mutia Vapestore : Check Out", JOptionPane.WARNING_MESSAGE);
            }
            
        }
        setProductDetail();
    }//GEN-LAST:event_checkOutBtnMouseClicked

    private void troliTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_troliTblMouseClicked
        if (!(troliTbl.getValueAt(troliTbl.getSelectedRow(), troliTbl.getSelectedColumn()).equals(""))) {
            editJumlahBtn.setEnabled(true);
            hapusProdukBtn.setEnabled(true);
        }
    }//GEN-LAST:event_troliTblMouseClicked

    private void editJumlahBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editJumlahBtnMouseClicked
        
        String editJumlah = JOptionPane.showInputDialog("Masukan Jumlah Barang Yang Akan Dibeli\n(Minimal 1 dan Maksimal " + myDao.stokProduk(myMod, ""));
        if (!checkAngka(editJumlah) || Integer.parseInt(editJumlah) < 1 || Integer.parseInt(editJumlah) > myDao.stokProduk(myMod, "")) {
            JOptionPane.showMessageDialog(null, "Inputan Tidak Valid", "Mutia Vapestore : Troli", JOptionPane.WARNING_MESSAGE);
        } else {
            myDao.updateKeranjangJual(troliTbl.getValueAt(troliTbl.getSelectedRow(),0).toString(), Integer.parseInt(troliTbl.getValueAt(troliTbl.getSelectedRow(),1).toString()), Integer.parseInt(editJumlah),Integer.parseInt(troliTbl.getValueAt(troliTbl.getSelectedRow(),1).toString())* Integer.parseInt(editJumlah) );
            setTroliTbl();
        }
        editJumlah = "";
        editJumlahBtn.setEnabled(false);
        hapusProdukBtn.setEnabled(false);
    }//GEN-LAST:event_editJumlahBtnMouseClicked

    private void hapusProdukBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusProdukBtnMouseClicked
        int res = JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Menghapus Produk Ini Dari Troli ?", "Mutia Vapestore : Troli", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (res == JOptionPane.YES_OPTION) {
            if(!troliTbl.getValueAt(troliTbl.getSelectedRow(), 0).toString().equals("")){
                myDao.deleteKeranjangJual(troliTbl.getValueAt(troliTbl.getSelectedRow(), 0).toString());
                setTroliTbl();
            }
        }
        editJumlahBtn.setEnabled(false);
        hapusProdukBtn.setEnabled(false);
    }//GEN-LAST:event_hapusProdukBtnMouseClicked

    private void pembelianBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembelianBtnMouseClicked
        PembelianFrame pf = new PembelianFrame(myMod);
        this.dispose();
    }//GEN-LAST:event_pembelianBtnMouseClicked

    private void serviceBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serviceBtnMouseEntered
        serviceBtn.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_serviceBtnMouseEntered

    private void serviceBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serviceBtnMouseExited
        serviceBtn.setBackground(new Color(153, 0, 51));
    }//GEN-LAST:event_serviceBtnMouseExited

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        int res = JOptionPane.showConfirmDialog(null, "Ingin Keluar", "Mutia Vapestore : Login", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (res == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        exitBtn.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        exitBtn.setBackground(new Color(153, 0, 51));
    }//GEN-LAST:event_exitBtnMouseExited

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBtnActionPerformed

    private void showDataProdukBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showDataProdukBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_showDataProdukBtnMouseEntered

    private void showDataProdukBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDataProdukBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showDataProdukBtnActionPerformed

    private void serviceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serviceBtnMouseClicked
        ServiceFrame sf = new ServiceFrame(myMod);
        this.dispose();
    }//GEN-LAST:event_serviceBtnMouseClicked
  
    public void run() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        this.setTitle("MUTIA VAPESTORE");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(0);

        PenjualanDialog.setTitle("Mutia Vapestore : Penjualan");
        PenjualanDialog.setModal(true);
        PenjualanDialog.setSize(600, 400);
        PenjualanDialog.setLocationRelativeTo(null);

        TroliDialog.setTitle("Mutia Vapestore : Penjualan");
        TroliDialog.setSize(600, 500);
        TroliDialog.setLocationRelativeTo(null);
        TroliDialog.setResizable(false);
        try {
            img = Toolkit.getDefaultToolkit().createImage(myDao.frameLogo(1));
            imgIcn = new ImageIcon(img);
            this.setIconImage(img);
            PenjualanDialog.setIconImage(img);
            TroliDialog.setIconImage(img);
        } catch (SQLException ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FullSizeImage;
    private javax.swing.JDialog PenjualanDialog;
    private javax.swing.JDialog TroliDialog;
    private javax.swing.JButton beliSekarangBtn;
    private javax.swing.JButton checkOutBtn;
    private javax.swing.JButton editJumlahBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel gambarCont;
    private javax.swing.JButton hapusProdukBtn;
    private javax.swing.JComboBox<String> hargaCB;
    private javax.swing.JLabel hargaTF;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel imageCont;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jumlahOkBtn;
    private javax.swing.JButton katalogBtn;
    private javax.swing.JComboBox<String> kategoriCB;
    private javax.swing.JLabel kategoriTF;
    private javax.swing.JButton lihatGambarPenuhBtn;
    private javax.swing.JLabel logoContainer;
    private javax.swing.JLabel namaTF;
    private javax.swing.JButton pembelianBtn;
    private javax.swing.JComboBox<String> penjualanJumlahCB;
    private javax.swing.JLabel penjualanNamaProdukLbl;
    private javax.swing.JLabel penjualanSubHargaLbl;
    private javax.swing.JLabel penjualanTotalLbl;
    private javax.swing.JComboBox<String> produkCB;
    private javax.swing.JButton serviceBtn;
    private javax.swing.JButton setFilterBtn;
    private javax.swing.JButton showDataProdukBtn;
    private javax.swing.JLabel stokTF;
    private javax.swing.JButton tambahkanBtn;
    private javax.swing.JLabel totalTransaksiLbl;
    private javax.swing.JButton troliBtrn;
    private javax.swing.JTable troliTbl;
    // End of variables declaration//GEN-END:variables
}
